name: Simple Workflow

on:
  push:
    branches:

      - master
      - master-staging
      - master-production
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print message
      run: echo "Hello, world!"
